global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  components:
    proxy: false
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql
  auth:
    username: postgres
    password: postgres
  primary:
    initdb:
      scripts:
        create-dbs.sql: |
          CREATE DATABASE auth;
          CREATE DATABASE products;
          CREATE DATABASE jobs;

jobs:
  enabled: true
  replicas: 1
  image: '057116648205.dkr.ecr.eu-central-1.amazonaws.com/jobber/jobs:latest'
  port:
    http: 3001
    grpc: 5002

executor:
  enabled: true
  replicas: 1
  image: '057116648205.dkr.ecr.eu-central-1.amazonaws.com/jobber/executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: '057116648205.dkr.ecr.eu-central-1.amazonaws.com/jobber/auth:latest'
  port:
    http: 3000
    grpc: 5000
  jwt:
   secret: 48zeBK4dfDH2qjCI9Z1iTq8XkfKcBxLj
   expirationMs: "28800000"

products:
  enabled: true
  replicas: 1
  image: '057116648205.dkr.ecr.eu-central-1.amazonaws.com/jobber/products:latest'
  port:
    http: 3003
    grpc: 5001
